# Generated by Django 2.2.7 on 2019-11-27 15:13

import article.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='media/article/article_default.jpeg', upload_to=article.utils.PathAndRename('C:\\Users\\zyraf\\Project\\RemoteProject\\Turttle\\media\\article')),
        ),
    ]
