# Generated by Django 2.2.7 on 2019-11-29 08:13

import article.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191128_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin_site',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='media/article/article_default.jpeg', upload_to=article.utils.PathAndRename('C:\\Users\\zyraf\\Projects\\RemoteDjango\\Turttle\\media\\article')),
        ),
    ]
